### PR TITLE
cli: add fleet file commands.

### PR DESCRIPTION
**Pull request by pwhelan**
# Summary of this proposal

Add fleet files commands for the fleet files API introduced by calyptia/cloud#1089.

## Asana task(s) link.

https://app.asana.com/0/1205296323611471/1205423874566066/f

## Notes for the reviewer

I mostly did a copy/paste of the pipeline files API. I tested at least the listing, retrieving and updating files via the CLI.

This PR will not work until the APIs are introduced in calyptia/api.

### CODE REVIEW

**Review by jasmingacic — APPROVED** [review]
Looking good

p.s. don't expect e2e to pass as it is currently broken

**Comment by patrick-stephens** [comment]
Can we add some tests to verify it @pwhelan ?

**Comment by pwhelan** [comment]
> Can we add some tests to verify it @pwhelan ?

calyptia/cli is totally void of tests. Most of the testing is done in cloud-e2e, If I am not mistaken.

For what it's worth, IWFM (tm) ... And it is mostly a copy/paste of the pipeline files command.

I was thinking of dedicating myself to adding end to end tests for fleet files next week, unless I'm needed elsewhere.

**Comment by pwhelan** [comment]
There is still an error in the [cloud logging test](https://github.com/calyptia/cli/actions/runs/6548782176/job/17784225834?pr=611#step:15:308):

```
2023-10-17T14:58:50.3509039Z not ok 23 Operator - Cluster logging check in 28430ms
2023-10-17T14:58:50.3520544Z # (from function `assert_success' in file tools/bats/lib/bats-assert/src/assert.bash, line 114,
2023-10-17T14:58:50.3524677Z #  in test file bats/operator/basic.bats, line 143)
2023-10-17T14:58:50.3544039Z #   `assert_success' failed
2023-10-17T14:58:50.3553473Z # Setup
2023-10-17T14:58:50.3559450Z # Local cloud deployed and token retrieved: eyJUb2tlbklEIjoiOTQ4OGUwYWEtOWYwYi00NDQzLWJhYmUtN2U0YTNhN2NlNDU1IiwiUHJvamVjdElEIjoiZTJlNzBiYWUtZGU4YS00YWE4LTg5NDUtZDE2YzUwODNjOTExIn0.gdQxoeOXn2dVn1evFYw3IO_Z4WUAhe1bPQx9n1k4-Skt-uiGOqm3_UJQJmWQczWc
2023-10-17T14:58:50.3562144Z # Cloud deployed and port forward set up: http://127.0.0.1:31075
2023-10-17T14:58:50.3563095Z # End of setup
2023-10-17T14:58:50.3563830Z # Valid expression. Verification in progress...
2023-10-17T14:58:50.3564849Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3566089Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3567597Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3568869Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3570089Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3571289Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3572515Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3573723Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3574860Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3576857Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3580422Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3581526Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3585929Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3591812Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3596932Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3602633Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3608021Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3613362Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3619013Z # No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3624483Z # Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3631233Z #
2023-10-17T14:58:50.3631707Z # -- command failed --
2023-10-17T14:58:50.3632169Z # status : 3
2023-10-17T14:58:50.3632574Z # output (21 lines):
2023-10-17T14:58:50.3633099Z #   Valid expression. Verification in progress...
2023-10-17T14:58:50.3651028Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3652497Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3653789Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3655079Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3656824Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3657999Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3659160Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3660361Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3661487Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3662666Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3663854Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3664977Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3666144Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3667370Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3668519Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3669704Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3670819Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3672443Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3673524Z #   No resource of type 'pods' was found with the name 'cluster-logging-*'.
2023-10-17T14:58:50.3674560Z #   Expected 1 pods named cluster-logging-* to have this value (running). Found 0.
2023-10-17T14:58:50.3675343Z # --
2023-10-17T14:58:50.3675675Z #
2023-10-17T14:58:50.3676022Z # Teardown
2023-10-17T14:58:50.3676581Z # NAME                                                       READY   STATUS    RESTARTS   AGE
2023-10-17T14:58:50.3677767Z # pod/calyptia-cloud-7c9d7d9bcb-8rj2g                        2/2     Running   0          60s
2023-10-17T14:58:50.3687281Z # pod/calyptia-core-controller-manager-84b98b8966-58jkf      1/1     Running   0          44s
2023-10-17T14:58:50.3688725Z # pod/calyptia-core-instance-core-instance-78845b95c-6rcn9   2/2     Running   0          32s
2023-10-17T14:58:50.3689620Z #
2023-10-17T14:58:50.3690339Z # NAME                                                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
2023-10-17T14:58:50.3691583Z # service/calyptia-cloud                                     ClusterIP   10.96.100.127   <none>        80/TCP              60s
2023-10-17T14:58:50.3693149Z # service/calyptia-core-controller-manager-metrics-service   ClusterIP   10.96.178.122   <none>        8443/TCP,8080/TCP   44s
2023-10-17T14:58:50.3694867Z # service/calyptia-core-instance-metrics-core-instance       ClusterIP   10.96.244.141   <none>        15334/TCP           32s
2023-10-17T14:58:50.3695905Z #
2023-10-17T14:58:50.3703718Z # NAME                                                   READY   UP-TO-DATE   AVAILABLE   AGE
2023-10-17T14:58:50.3705094Z # deployment.apps/calyptia-cloud                         1/1     1            1           60s
2023-10-17T14:58:50.3711673Z # deployment.apps/calyptia-core-controller-manager       1/1     1            1           44s
2023-10-17T14:58:50.3713013Z # deployment.apps/calyptia-core-instance-core-instance   1/1     1            1           32s
2023-10-17T14:58:50.3713853Z #
2023-10-17T14:58:50.3719940Z # NAME                                                             DESIRED   CURRENT   READY   AGE
2023-10-17T14:58:50.3721243Z # replicaset.apps/calyptia-cloud-7c9d7d9bcb                        1         1         1       60s
2023-10-17T14:58:50.3723037Z # replicaset.apps/calyptia-core-controller-manager-84b98b8966      1         1         1       44s
2023-10-17T14:58:50.3729163Z # replicaset.apps/calyptia-core-instance-core-instance-78845b95c   1         1         1       32s
```

I think this is irrelevant to this PR.

**Review by jasmingacic — APPROVED** [review]
don't expect e2e to pass

**Review by niedbalski — APPROVED** [review]
LGTM

**Pull request merged**
