### PR TITLE
added cli subcommands update operator and update core_instance

### PR DESCRIPTION
**Pull request by jasmingacic**
# Summary of this proposal

```
# go run main.go update operator -h
Update core operator

Usage:
  calyptia update operator [flags]

Aliases:
  operator, opr
...
```

```
# go run main.go update core_instance operator -h 
update a core instance operator

Usage:
  calyptia update core_instance operator CORE_INSTANCE [flags]

Aliases:
  operator, opr
```
## Asana task(s) link.

https://app.asana.com/0/1205296323611471/1205329297259871

### CODE REVIEW

**Review by niedbalski — CHANGES_REQUESTED** [review]
Tried to upgrade operator

```shell
➜ cli (update_core-operator_core-instance) ✔ ./cli update operator --version v1.0.13
Core operator manager successfully installed.
➜ cli (update_core-operator_core-instance) ✔ kubectl get pods -A
NAMESPACE            NAME                                               READY   STATUS             RESTARTS   AGE
default              calyptia-core-controller-manager-6c8696f65-tlb6d   0/1     Running            0          22s
default              calyptia-core-controller-manager-8dd7c7bd5-dzshx   0/1     InvalidImageName   0          4s
```
Got 

```
  ----     ------         ----              ----               -------
  Normal   Scheduled      15s               default-scheduler  Successfully assigned default/calyptia-core-controller-manager-8dd7c7bd5-dzshx to kind-control-plane
  Warning  InspectFailed  0s (x3 over 15s)  kubelet            Failed to apply default image tag "ghcr.io/calyptia/core-operator:ghcr.io/calyptia/core-operator:v1.0.13": couldn't parse image reference "ghcr.io/calyptia/core-operator:ghcr.io/calyptia/core-operator:v1.0.13": invalid reference format
```

Then a normal upgrade 

```
  Warning  Failed         0s (x3 over 15s)  kubelet            Error: InvalidImageName
➜ cli (update_core-operator_core-instance) ✔ ./cli update operator
Core operator manager successfully installed.
➜ cli (update_core-operator_core-instance) ✔ kubectl get pods -A
NAMESPACE            NAME                                                READY   STATUS             RESTARTS   AGE
default              calyptia-core-controller-manager-69b4f84fd8-jj2tv   0/1     InvalidImageName   0          3s
default              calyptia-core-controller-manager-6c8696f65-tlb6d    1/1     Running            0          64s
```

Image is set to 

```
    Image:         ghcr.io/calyptia/core-operator:ghcr.io/calyptia/core-operator:v1.0.14
```

Also, the output says installed, while this should say upgraded.

Also, reports as successful whereas the pod is in error state (check the status before)

```
Core operator manager successfully installed.
```

**Review by niedbalski — CHANGES_REQUESTED** [review]
Now the image's tag is appended correctly, but its failing to ensure the deployment is ready (including the --wait flag doesn't work)

```➜ cli (update_core-operator_core-instance) ✔ ./cli update operator --wait
Core operator manager successfully updated."
```

Also

```
➜ cli (update_core-operator_core-instance) ✔ ./cli update operator --version v1.2.9
Core operator manager successfully updated.
➜ cli (update_core-operator_core-instance) ✔ kubectl get pods -A
NAMESPACE            NAME                                               READY   STATUS         RESTARTS   AGE
default              calyptia-core-controller-manager-6c8696f65-kmkb5   1/1     Running        0          65s
default              calyptia-core-controller-manager-95c8987df-k5dxk   0/1     ErrImagePull   0          7s
```

Also make this part of the code smarter, so that if is a valid semver but doesn't have a "v" prefix, add it by default instead of printing the error message.

```
➜ cli (update_core-operator_core-instance) ✔ ./cli update operator --version 1.2.9
Error: version string should start with prefix v
```

**Comment by jasmingacic** [comment]
When failing 
```
# go run main.go update core_instance operator correct-sailor-174e  --version 1.0.144
Waiting for core-instance to update...
Error: an error occurred: could not update core-instance: failed while waiting for deployment to start: 
Reasons: 
* Pod calyptia-correct-sailor-174e-default-sync-6c74698cc6-b5psw, Message: rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/calyptia/core-operator/sync-from-cloud:v1.0.144": failed to resolve reference "ghcr.io/calyptia/core-operator/sync-from-cloud:v1.0.144": ghcr.io/calyptia/core-operator/sync-from-cloud:v1.0.144: not found
rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/calyptia/core-operator/sync-to-cloud:v1.0.144": failed to resolve reference "ghcr.io/calyptia/core-operator/sync-to-cloud:v1.0.144": ghcr.io/calyptia/core-operator/sync-to-cloud:v1.0.144: not found'

exit status 1
```

```
# go run main.go update operator --version 1.0.144
Waiting for core-operator to update...
Error: an error occurred: could not update core-operator: failed while waiting for deployment to start: 
Reasons: 
* Pod calyptia-core-controller-manager-7cf68ddb84-l7nl4, Message: rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/calyptia/core-operator:v1.0.144": failed to resolve reference "ghcr.io/calyptia/core-operator:v1.0.144": ghcr.io/calyptia/core-operator:v1.0.144: not found'

exit status 1
```

When succeeding 
```
# go run main.go update core_instance operator correct-sailor-174e  --version 1.0.14
Waiting for core-instance to update...
calyptia-core instance version updated to version v1.0.14
```

```
# go run main.go update operator --version 1.0.14
Waiting for core-operator to update...
Core operator manager successfully updated to version v1.0.14
```

**Review by niedbalski — APPROVED** [review]
LGTM

**Pull request merged**
